- name: Update package cache & dist-upgrade packages
  apt:
    upgrade: "{{ apt_upgrade }}"
    update_cache: yes
    cache_valid_time: 3600
    force_apt_get: true
    autoclean: true

- name: Clean apt.
  command: apt-get clean
  changed_when: false